name: Tymy.CZ CI

on:
  push:

jobs:
  static-analysis:
      name: Static analysis
      runs-on: self-hosted
      
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "Compose"
          run: /usr/bin/php7.4 /usr/local/bin/composer install --dev
          
        - name: "PHPCs"
          run: vendor/bin/phpcs
          
        - name: "PHPStan"
          run: vendor/bin/phpstan