name: Tymy.CZ CI

on:
  push:

jobs:
  static-analysis-PHP74:
      name: Static analysis on PHP 7.4
      runs-on: self-hosted
      
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "Composer"
          run: /usr/bin/php7.4 /usr/bin/composer install
          
        - name: "PHP Code Sniffer"
          run: /usr/bin/php7.4 vendor/bin/phpcs
          
        - name: "PHP Stan"
          run: /usr/bin/php7.4 vendor/bin/phpstan