name: Tymy.CZ CI

on:
  push:
  pull_request:

jobs:
  phpstan:
      name: PHPStan Static Analysis
      runs-on: php-alpine:latest
      
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "PHPStan"
          run: vendor/bin/phpstan