name: Tymy.CZ CI

on:
  push:

jobs:
  static-analysis:
      name: Static analysis
      runs-on: self-hosted
      
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "Compose"
          with:
            php-version: '7.4'
        - run: composer install --dev
          
        - name: "PHPCs"
          with:
            php-version: '7.4'
        - run: vendor/bin/phpcs
          
        - name: "PHPStan"
          with:
            php-version: '7.4'
        - run: vendor/bin/phpstan