name: Tymy.CZ CI

on:
  push:

jobs:
  static-analysis-PHP74:
      name: Static analysis on PHP 7.4
      runs-on: self-hosted
      
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          
        - name: "Compose"
          run: composer install --dev
          
        - name: "PHPCs"
          run: vendor/bin/phpcs
          
        - name: "PHPStan"
          run: vendor/bin/phpstan
