name: Tymy.CZ CI

on:
  push:
  pull_request:

jobs:
  phpstan:
      name: PHPStan Static Analysis
      runs-on: self-hosted
      
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          run: composer install --dev
          
        - name: "PHPStan"
          run: vendor/bin/phpstan
  phpcs:
      name: PHP Code Sniffer
      runs-on: self-hosted
      
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          run: composer install --dev
          
        - name: "PHPCs"
          run: vendor/bin/phpcs